// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH46C7r5nB9rkDDfcHUtGk8j_27WBp-Yw',
    appId: '1:700810417382:web:23b5332ff9bef66f305727',
    messagingSenderId: '700810417382',
    projectId: 'chatapp-2423e',
    authDomain: 'chatapp-2423e.firebaseapp.com',
    storageBucket: 'chatapp-2423e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSuI-wI_3dKjpybHygXVIECF-lREFFePY',
    appId: '1:700810417382:android:ea360c29ae7da687305727',
    messagingSenderId: '700810417382',
    projectId: 'chatapp-2423e',
    storageBucket: 'chatapp-2423e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcMNuFXkOznPUjJS4JETapGcdTjGXE_nQ',
    appId: '1:700810417382:ios:89fe69515c005a53305727',
    messagingSenderId: '700810417382',
    projectId: 'chatapp-2423e',
    storageBucket: 'chatapp-2423e.appspot.com',
    iosClientId: '700810417382-94mnsnci08ampeb6eh9j136146d3c1mq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );
}
